In [48]:
import numpy as np
import pandas as pd

In [49]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [50]:

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/train.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
df = pd.read_csv('/content/drive/MyDrive/train.csv', usecols=['Age','Fare','Survived'])

In [52]:
df.dropna(inplace=True)

In [53]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [54]:
df = pd.read_csv('/content/drive/MyDrive/train.csv',
                 usecols=['Age','Fare','Survived','SibSp','Parch'])

# create family feature
df['family'] = df['SibSp'] + df['Parch']

# now drop them
df.drop(columns=['SibSp','Parch'], inplace=True)

In [55]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [56]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [57]:
X_train.head()

      Age     Fare  family
331  45.5  28.5000       0
733  23.0  13.0000       0
382  32.0   7.9250       0
704  26.0   7.8542       1
813   6.0  31.2750       6

In [58]:
from sklearn.preprocessing import Binarizer

In [59]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [60]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [61]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       0.0  45.5   28.5000
1       0.0  23.0   13.0000
2       0.0  32.0    7.9250
3       1.0  26.0    7.8542
4       1.0   6.0   31.2750
..      ...   ...       ...
707     0.0  21.0    7.6500
708     0.0   NaN   31.0000
709     1.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [62]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6368715083798883

In [63]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6532209737827716)